One file for apply and destroy
ADORSYS-GIS/webank-devops pull request #33
Opened 2024-12-12 16:41 UTC by Koufan-De-King

2024-12-12 19:21 UTC, stephane-segning requested changes

2024-12-12 19:21 UTC, stephane-segning commented on .github/workflows/deploy.yaml
> +      url: https://${{ vars.DOMAIN_NAME }}
Remove the url from this one, as we're destroying

2024-12-12 19:21 UTC, stephane-segning commented on .github/workflows/deploy.yaml
> +            description: "Environment to be changed"
Do you need this include block?

2024-12-12 19:25 UTC, stephane-segning requested changes
We don't want a single file for apply and destroy. We want them separated

2024-12-13 06:35 UTC, Koufan-De-King commented
Okay @stephane-segning.
I thought it a wise idea for making destroy use the same sate as apply.
Will close the PR now.

2024-12-13 06:35 UTC, closed without merging